// <auto-generated />
using HRPayroll.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable
#pragma warning disable

namespace HRPayroll.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.UseIdentityColumns();

            modelBuilder.Entity("HRPayroll.Core.Entities.Attendance", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("Id").UseIdentityColumn();
                b.Property<TimeOnly?>("CheckIn").HasColumnType("time");
                b.Property<TimeOnly?>("CheckOut").HasColumnType("time");
                b.Property<System.DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateOnly>("Date").HasColumnType("date");
                b.Property<int>("EmployeeId").HasColumnType("int");
                b.Property<decimal>("OTHours").HasColumnType("decimal(5,2)");
                b.Property<string>("SiteProject").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Remarks").HasColumnType("nvarchar(max)");
                b.Property<string>("Transport").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<System.DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.Property<decimal>("WorkHours").HasColumnType("decimal(5,2)");
                b.HasKey("Id");
                b.HasIndex("EmployeeId", "Date").IsUnique();
                b.ToTable("SLE_Attendances");
            });

            modelBuilder.Entity("HRPayroll.Core.Entities.AttendanceLookup", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("Id").UseIdentityColumn();
                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<System.DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasDefaultValue(true).HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("SortOrder").ValueGeneratedOnAdd().HasDefaultValue(0).HasColumnType("int");
                b.Property<System.DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Category", "Name").IsUnique();
                b.ToTable("SLE_AttendanceLookups");
            });

            modelBuilder.Entity("HRPayroll.Core.Entities.Department", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("Id").UseIdentityColumn();
                b.Property<System.DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.ToTable("SLE_Departments");
            });

            modelBuilder.Entity("HRPayroll.Core.Entities.Employee", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("Id").UseIdentityColumn();
                b.Property<decimal>("BasicSalary").HasColumnType("decimal(18,2)");
                b.Property<System.DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("DepartmentId").HasColumnType("int");
                b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(450)");
                b.Property<string>("EmployeeCode").IsRequired().HasColumnType("nvarchar(450)");
                b.Property<string>("FirstName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateOnly>("JoinDate").HasColumnType("date");
                b.Property<string>("LastName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("OTRatePerHour").HasColumnType("decimal(18,2)");
                b.Property<string>("Phone").HasColumnType("nvarchar(max)");
                b.Property<string>("Position").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("StandardWorkHours").HasColumnType("int");
                b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<System.DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("DepartmentId");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("EmployeeCode").IsUnique();
                b.ToTable("SLE_Employees");
            });

            modelBuilder.Entity("HRPayroll.Core.Entities.PayrollRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("Id").UseIdentityColumn();
                b.Property<int>("AbsentDays").HasColumnType("int");
                b.Property<decimal>("BasicSalary").HasColumnType("decimal(18,2)");
                b.Property<decimal>("DailyRate").HasColumnType("decimal(18,2)");
                b.Property<decimal>("Deductions").HasColumnType("decimal(18,2)");
                b.Property<int>("EmployeeId").HasColumnType("int");
                b.Property<decimal>("GrossSalary").HasColumnType("decimal(18,2)");
                b.Property<int>("LeaveDays").HasColumnType("int");
                b.Property<int>("Month").HasColumnType("int");
                b.Property<decimal>("NetSalary").HasColumnType("decimal(18,2)");
                b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                b.Property<decimal>("OTAmount").HasColumnType("decimal(18,2)");
                b.Property<int>("PresentDays").HasColumnType("int");
                b.Property<System.DateTime>("ProcessedAt").HasColumnType("datetime2");
                b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("TotalOTHours").HasColumnType("decimal(8,2)");
                b.Property<decimal>("TotalWorkHours").HasColumnType("decimal(8,2)");
                b.Property<System.DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.Property<int>("WorkingDays").HasColumnType("int");
                b.Property<int>("Year").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("EmployeeId", "Month", "Year").IsUnique();
                b.ToTable("SLE_PayrollRecords");
            });

            modelBuilder.Entity("HRPayroll.Core.Entities.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("Id").UseIdentityColumn();
                b.Property<System.DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("PasswordSalt").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Role").IsRequired().HasDefaultValue("Admin").HasColumnType("nvarchar(max)");
                b.Property<string>("Username").IsRequired().HasColumnType("nvarchar(450)");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.ToTable("SLE_Users");
            });
#pragma warning restore 612, 618
        }
    }
}
